language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev --deploy
script:
  - python manage.py test --settings=eventowl.settings_test
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv