version: '3'
services:
  backend:
    build: .
    environment:
      - EVENTFUL_API_KEY=${EVENTFUL_API_KEY}
      - REDIS_URL=redis://cache:6379/1
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SPOTIFY_URL=${SPOTIFY_URL}
      - DATABASE_URL=postgres://dbuser:dbpassword@db/postgres
      - DEBUG=true
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    working_dir: /code
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:8000 &
               python3 manage.py qcluster"
    links:
    - cache
    - db
  frontend:
    environment:
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_URL=${SPOTIFY_URL}
    image: node:8
    volumes:
    - .:/code
    working_dir: /code
    command: npm start
  cache:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword