version: '3'
services:
  backend:
    build: .
    environment:
      - EVENTFUL_API_KEY=${EVENTFUL_API_KEY}
      - REDIS_URL=redis://redis:6379/1
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    working_dir: /code
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:8000 &
               python3 manage.py qcluster"
    links:
    - redis
    - postgres
  frontend:
    image: node:8
    volumes:
    - .:/code
    working_dir: /code
    command: npm start
  redis:
    image: redis
  postgres:
    image: postgres