# Generated by Django 2.0.4 on 2018-04-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0002_auto_20180407_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='url',
            field=models.URLField(default='https://test.com'),
            preserve_default=False,
        ),
    ]
