# Generated by Django 2.0.4 on 2018-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0003_auto_20180408_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
