# Generated by Django 2.0.4 on 2018-04-12 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concertowl', '0004_auto_20180408_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.URLField(default='/static/default_artist.jpg'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.URLField(default='/static/default_event.jpg'),
        ),
    ]
