# Generated by Django 2.0.4 on 2018-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0006_auto_20180415_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
