# Generated by Django 2.0.4 on 2018-04-16 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0007_auto_20180415_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='artists', to='concertowl.Artist'),
        ),
    ]
