# Generated by Django 2.0.4 on 2018-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0008_auto_20180416_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
