# Generated by Django 2.0.4 on 2018-04-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0010_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='concertowl.Event'),
        ),
    ]
