# Generated by Django 2.0.4 on 2018-04-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0011_auto_20180422_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
