# Generated by Django 2.0.4 on 2018-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0016_userprofile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
