# Generated by Django 2.0.5 on 2018-05-10 14:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0018_userprofile_spotify_import_running'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='artist',
            managers=[
                ('artists', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
