# Generated by Django 2.0.5 on 2018-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0019_auto_20180510_1409'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='artist',
            managers=[
            ],
        ),
    ]
